# Generated by Django 3.1.4 on 2020-12-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201212_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
